apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 5 # Full replicas for production
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.1 # Production-ready image
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 5m} # Initial small canary, observe
        - analysis: # Initial analysis
            templates:
              - templateName: http-error-rate-check
            args:
              - name: namespace
                value: my-app # Target namespace on prod-cluster
        - pause: {} # <--- MANUAL APPROVAL POINT IN ARGO CD UI / CLI
        # This step requires manual intervention to proceed.
        # Use 'argo rollouts promote -n my-app nginx-rollout' or the Argo CD UI.
        - setWeight: 50
        - pause: {duration: 10m} # Longer observation
        - analysis: # Second analysis after 50% traffic
            templates:
              - templateName: http-error-rate-check
            args:
              - name: namespace
                value: my-app
        - setWeight: 100

